### PR TITLE
SAPHanaSR-monitor: fix tolower() issue, which seems to be an artifact from a2p (Awk to Perl)

### PR DESCRIPTION
**Pull request by oalbrigt**
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=39267

### CODE REVIEW

**Comment by oalbrigt** [comment]
It's not available in Perl, so it makes the script fail.

It seems like this was already fixed in `SAPHanaSR-showAttr` in this repo vs the main SAPHanaSR repo.

**Comment by oalbrigt** [comment]
```
$ SAPHanaSR-monitor
Undefined subroutine &main::tolower called at ./SAPHanaSR-monitor.tmp line 222.
````

**Comment by fmherschel** [comment]
> ```
> $ SAPHanaSR-monitor
> Undefined subroutine &main::tolower called at ./SAPHanaSR-monitor.tmp line 222.
> ```

would be lc() ok  with you? I need the conversion from HA1 to ha1.

**Comment by oalbrigt** [comment]
That seems to work fine, so I'll update the PR accordingly.

I guess you'll want it put back in `SAPHanaSR-showAttr` as well.

**Comment by oalbrigt** [comment]
Ah. It's already correct there. I'll just update this.

Do you want me to make a PR against the SAPHanaSR repo as well?

**Comment by oalbrigt** [comment]
I've force-pushed the updated commit to `lc()`.

**Comment by fmherschel** [comment]
Meging the lc() related PR

**Pull request merged**
