### PR TITLE
renamed:    SAPHanaSR-call_monitor to SAPHanaSR-call-monitor

### PR DESCRIPTION
**Pull request by fmherschel**
renamed:    SAPHanaSR-call_monitor to SAPHanaSR-call-monitor to better match current tool name convention

### CODE REVIEW

**Comment by fmherschel** [comment]
Sorry for this third PR ;-)

**Comment by fmherschel** [comment]
Upps - I also need to change the spec file , so please wait a second ..

**Comment by fmherschel** [comment]
Updated spec file so now we would be fine for a review :)

**Review by angelabriel — APPROVED** [review]
Looks good to me, thanks

**Pull request merged**
